CREATE TABLE users(
id INT(32) AUTO_INCREMENT,
usename VARCHAR(128) NOT NULL,
PASSWORD VARCHAR(128) NOT NULL,
email VARCHAR(128) NOT NULL,
birthday VARCHAR(128) NOT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
